package service.views;
import inventory.views.View;
import service.viewmodels.ServiceViewModel;
import service.views.ServiceMainView;
import java.time.*;
import javax.swing.JOptionPane;
import java.util.regex.*;

public class AddServiceAppointmentView extends javax.swing.JFrame implements View
{
    
    protected ServiceViewModel viewModel;
    protected ServiceMainView main_view;    
    
    /** Creates new form AddServiceAppointmentView */
    public AddServiceAppointmentView(ServiceViewModel svm, ServiceMainView main_view) 
    {
        viewModel = svm;
        this.main_view = main_view;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        appointment_year_textbox = new javax.swing.JTextField();
        appointment_day_textbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        appointment_month_textbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments_text_area = new javax.swing.JTextArea();
        comments_label = new javax.swing.JLabel();
        vin_label = new javax.swing.JLabel();
        vin_textfield = new javax.swing.JTextField();
        make_textfield = new javax.swing.JTextField();
        make_label = new javax.swing.JLabel();
        model_textfield = new javax.swing.JTextField();
        model_label = new javax.swing.JLabel();
        color_textfield = new javax.swing.JTextField();
        color_label = new javax.swing.JLabel();
        save_new_appointment_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("AddServiceAppointmentView");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Create New Appointment"));
        jPanel1.setName(""); // NOI18N

        email_label.setText("Customer Email:");

        jLabel11.setText("/");

        jLabel8.setText("/");

        date_label.setText("Date:");

        comments_text_area.setColumns(20);
        comments_text_area.setRows(5);
        jScrollPane1.setViewportView(comments_text_area);

        comments_label.setText("Comments:");

        vin_label.setText("Vin Number:");

        make_label.setText("Car Make:");

        model_label.setText("Car Model:");

        color_label.setText("Car Color:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vin_label)
                            .addComponent(date_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(appointment_month_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(appointment_day_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appointment_year_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(vin_textfield)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(make_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(model_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(color_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(color_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(model_textfield)
                                    .addComponent(make_textfield))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(comments_label)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label)
                            .addComponent(comments_label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appointment_month_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointment_day_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(appointment_year_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vin_label)
                            .addComponent(vin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(make_label)
                            .addComponent(make_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model_label)
                            .addComponent(model_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color_label)
                            .addComponent(color_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        save_new_appointment_button.setText("Save");
        save_new_appointment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_new_appointment_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_new_appointment_button)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(save_new_appointment_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        this.setLocationRelativeTo(null);
    }// </editor-fold>                        

    //public CarModel(String vin, String make, String model, String color)
    //public void addAppointment(String email, String vin, String make, String model, String color, LocalDate date, String comments)
    private void save_new_appointment_buttonActionPerformed(java.awt.event.ActionEvent evt) 
    {                                                            
      String email = email_textfield.getText();
      if(email.length() == 0) {JOptionPane.showMessageDialog(this, "Please specify an email address."); return;}
      
      Pattern p = Pattern.compile(".+@.+\\.com");
      Matcher m = p.matcher(email);
      
      if(!m.find())
      {
        JOptionPane.showMessageDialog(this, "Please specify a valid email address.");
        return;
      }
      
      int month;
      int day;
      int year;      
      try
      {
          month = Integer.parseInt(appointment_month_textbox.getText());
          day = Integer.parseInt(appointment_day_textbox.getText());
          year = Integer.parseInt(appointment_year_textbox.getText());
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this, "Invalid date entered."); 
          return;
      }
      
      LocalDate date = LocalDate.of(year,month,day);
      
      String vin = vin_textfield.getText();
      String make = make_textfield.getText();
      String model = model_textfield.getText();
      String color = color_textfield.getText();
      
      if(vin.length() == 0 || make.length() == 0 || model.length() == 0 || color.length() == 0)
      {
          JOptionPane.showMessageDialog(this, "Vehicle information incomplete."); 
          return;
      }
      
      String comments = comments_text_area.getText();
      
      viewModel.addAppointment(email, vin, make, model, color, date, comments);
      
      ServiceMainView updated_main_view = new ServiceMainView(viewModel);
      main_view.dispose();
      viewModel.switchView(updated_main_view);
      this.setVisible(false);
      this.dispose();
        
    }                                                           
  
    public String render()
    {
      initComponents();
      this.setVisible(true);
      return "AddServiceAppointmentView rendered.";
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JTextField appointment_day_textbox;
    private javax.swing.JTextField appointment_month_textbox;
    private javax.swing.JTextField appointment_year_textbox;
    private javax.swing.JLabel color_label;
    private javax.swing.JTextField color_textfield;
    private javax.swing.JLabel comments_label;
    private javax.swing.JTextArea comments_text_area;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel make_label;
    private javax.swing.JTextField make_textfield;
    private javax.swing.JLabel model_label;
    private javax.swing.JTextField model_textfield;
    private javax.swing.JButton save_new_appointment_button;
    private javax.swing.JLabel vin_label;
    private javax.swing.JTextField vin_textfield;
    // End of variables declaration                   
    
}
